// <auto-generated />
using System;
using System.Collections.Generic;
using Analytics.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analytics.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260516135105_UpdatePaymentConfig")]
    partial class UpdatePaymentConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Analytics")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analytics.Domain.Entities.Customer.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcquisitionCampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("AcquisitionChannel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("FirstOrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastOrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LifetimeValue")
                        .HasColumnType("numeric");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AcquisitionChannel")
                        .HasDatabaseName("IX_Customers_Tenant_Channel");

                    b.HasIndex("TenantId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_Tenant_External");

                    b.HasIndex("TenantId", "LastOrderDate")
                        .HasDatabaseName("IX_Customers_Tenant_LastOrderDate");

                    b.HasIndex("TenantId", "LifetimeValue")
                        .HasDatabaseName("IX_Customers_Tenant_LifetimeValue");

                    b.HasIndex("TenantId", "RegistrationDate")
                        .HasDatabaseName("IX_Customers_Tenant_RegistrationDate");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Customers_Tenant_Status");

                    b.ToTable("Customers", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Marketing.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("ActivePeriod", "Analytics.Domain.Entities.Marketing.Campaign.ActivePeriod#DateRange", b1 =>
                        {
                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("ActivePeriodEnd");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("ActivePeriodStart");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Budget", "Analytics.Domain.Entities.Marketing.Campaign.Budget#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BudgetAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("BudgetCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Channel")
                        .HasDatabaseName("IX_Campaigns_Tenant_Channel");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Campaigns_Tenant_Name");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Campaigns_Tenant_Status");

                    b.ToTable("Campaigns", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Marketing.MarketingExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer");

                    b.Property<int>("Leads")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MetricsRecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "Analytics.Domain.Entities.Marketing.MarketingExpense.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CampaignId")
                        .HasDatabaseName("IX_MarketingExpenses_Tenant_Campaign");

                    b.HasIndex("TenantId", "ExpenseDate")
                        .HasDatabaseName("IX_MarketingExpenses_Tenant_Date");

                    b.HasIndex("TenantId", "AdSource", "ExpenseDate")
                        .HasDatabaseName("IX_MarketingExpenses_Tenant_Source_Date");

                    b.ToTable("MarketingExpenses", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Order.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("TotalAmount", "Analytics.Domain.Entities.Order.Order.TotalAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId", "ExternalOrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_Tenant_ExternalId");

                    b.HasIndex("TenantId", "OrderDate")
                        .HasDatabaseName("IX_Orders_Tenant_OrderDate");

                    b.HasIndex("TenantId", "CustomerId", "OrderDate")
                        .HasDatabaseName("IX_Orders_Tenant_Customer_Date");

                    b.HasIndex("TenantId", "Status", "OrderDate")
                        .HasDatabaseName("IX_Orders_Tenant_Status_Date");

                    b.ToTable("Orders", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Order.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductExternalId");

                    b.ToTable("OrderItem", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Source.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId1");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_DataSources_Tenant_Name");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_DataSources_Tenant_Status");

                    b.HasIndex("TenantId", "Type")
                        .HasDatabaseName("IX_DataSources_Tenant_Type");

                    b.ToTable("DataSources", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Tenant.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ApiKeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenants_ApiKeyHash");

                    b.HasIndex("ApiKeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenants_ApiKeyPrefix");

                    b.HasIndex("CompanyName")
                        .HasDatabaseName("IX_Tenants_CompanyName");

                    b.HasIndex("Plan")
                        .HasDatabaseName("IX_Tenants_Plan");

                    b.ToTable("Tenants", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("PaidAmount", "Analytics.Domain.Entities.Transactions.Payment.PaidAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PaidAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("PaidCurrency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalAmount", "Analytics.Domain.Entities.Transactions.Payment.TotalAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_OrderId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Payments_Tenant_Status");

                    b.ToTable("Payments", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Transactions.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "Analytics.Domain.Entities.Transactions.PaymentTransaction.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_PaymentTransactions_PaymentId");

                    b.ToTable("PaymentTransactions", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users", "Analytics");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Order.Order", b =>
                {
                    b.HasOne("Analytics.Domain.Entities.Customer.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Order.OrderItem", b =>
                {
                    b.HasOne("Analytics.Domain.Entities.Order.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Source.DataSource", b =>
                {
                    b.HasOne("Analytics.Domain.Entities.Tenant.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Analytics.Domain.Entities.Tenant.Tenant", null)
                        .WithMany("DataSources")
                        .HasForeignKey("TenantId1");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Transactions.PaymentTransaction", b =>
                {
                    b.HasOne("Analytics.Domain.Entities.Transactions.Payment", null)
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Customer.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Order.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Tenant.Tenant", b =>
                {
                    b.Navigation("DataSources");
                });

            modelBuilder.Entity("Analytics.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
